export const LOGIN_TOKEN = 'token'
export const USERMENUS = 'userMenus'
export const USERINFO = 'userInfo'
export const CURRENT_ROUTE = 'current_route'
export const USER_ID = 'userId'
export const USER_ROLE_ID = 'roleId'
